-- ==========================================
-- 1. TIPOS E ENUMS
-- ==========================================
create type public.transaction_type as enum ('income', 'expense');

-- ==========================================
-- 2. TABELAS
-- ==========================================

-- Tabela: Users (Substitui auth.users para o bot)
create table public.users (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text not null unique,
  username text,
  first_name text,
  language_code text default 'pt-BR',
  is_allowed boolean default false
);

-- Tabela: Contas (Carteira, Banco, etc.)
create table public.accounts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.users(id) on delete cascade not null,
  name text not null,
  initial_balance numeric(12, 2) default 0.00,
  is_default boolean default false
);

-- Tabela: Categorias
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.users(id) on delete cascade not null,
  name text not null,
  icon text,
  type public.transaction_type not null default 'expense',
  is_editable boolean default true
);

-- Tabela: Transações
create table public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.users(id) on delete cascade not null,
  account_id bigint references public.accounts(id) on delete cascade not null,
  category_id bigint references public.categories(id) on delete set null,
  amount numeric(12, 2) not null,
  date date not null default CURRENT_DATE,
  description text,
  type public.transaction_type not null
);

-- ==========================================
-- 3. SEGURANÇA (Row Level Security)
-- ==========================================

alter table public.users enable row level security;
alter table public.accounts enable row level security;
alter table public.categories enable row level security;
alter table public.transactions enable row level security;

-- Policies for public.users
create policy "Enable read access for all users" on public.users for select using (true);
create policy "Enable insert for all users" on public.users for insert with check (true);
create policy "Enable update for all users" on public.users for update using (true);

-- Policies for other tables (using public.users id match not auth.uid anymore, strictly speaking)
-- NOTE: Since this is a bot and we might use service key or handle ID manually in query, 
-- we will allow all logic or strict logic based on user_id match. 
-- For simplicity in this bot context where backend handles auth, we keep RLS enabled but open for now
-- or we can enforce user_id checks if we had a logged in user.
-- For now, let's keep simple "true" policies or basic user checks if possible.
-- Since the bot backend acts as admin/service, RLS is mostly for safety if exposed.
-- We'll assume the backend uses the service role or we rely on the application logic.

create policy "Allow all on accounts" on public.accounts using (true);
create policy "Allow all on categories" on public.categories using (true);
create policy "Allow all on transactions" on public.transactions using (true);


-- ==========================================
-- 4. PERFORMANCE (Índices)
-- ==========================================
create index idx_transactions_user_date on public.transactions(user_id, date);
create index idx_transactions_account on public.transactions(account_id);
create index idx_categories_user on public.categories(user_id);


-- ==========================================
-- 5. AUTOMATIZAÇÃO (Trigger para Dados Padrão)
-- ==========================================

create or replace function public.handle_new_public_user()
returns trigger
language plpgsql
security definer
as $$
declare
  user_lang text;
  -- Definição dos dados padrão (Categorias E Contas)
  default_data jsonb := '{
    "pt-BR": {
      "categories": [
        {"name": "Alimentação", "icon": "🍔", "type": "expense"},
        {"name": "Transporte", "icon": "🚌", "type": "expense"},
        {"name": "Moradia", "icon": "🏠", "type": "expense"},
        {"name": "Salário", "icon": "💰", "type": "income"}
      ],
      "accounts": [
        {"name": "Padrão", "is_default": true},
      ]
    },
    "en": {
      "categories": [
        {"name": "Food", "icon": "🍔", "type": "expense"},
        {"name": "Transport", "icon": "🚌", "type": "expense"},
        {"name": "Housing", "icon": "🏠", "type": "expense"},
        {"name": "Salary", "icon": "💰", "type": "income"}
      ],
      "accounts": [
        {"name": "Default", "is_default": true},
      ]
    }
  }';
  
  -- Variáveis auxiliares
  selected_data jsonb;
  item jsonb;
begin
  -- 1. Detetar língua
  user_lang := coalesce(new.language_code, 'pt-BR');
  
  -- 2. Selecionar dados (Fallback para EN se não encontrar)
  selected_data := default_data->user_lang;
  IF selected_data IS NULL THEN
    selected_data := default_data->'en';
  END IF;

  -- 3. Criar Contas Padrão
  for item in SELECT * FROM jsonb_array_elements(selected_data->'accounts')
  loop
    insert into public.accounts (user_id, name, is_default)
    values (new.id, item->>'name', (item->>'is_default')::boolean);
  end loop;

  -- 4. Criar Categorias Padrão
  for item in SELECT * FROM jsonb_array_elements(selected_data->'categories')
  loop
    insert into public.categories (user_id, name, icon, type)
    values (new.id, item->>'name', item->>'icon', (item->>'type')::public.transaction_type);
  end loop;

  return new;
end;
$$;

create trigger on_public_user_created
  after insert on public.users
  for each row execute procedure public.handle_new_public_user();