-- ==========================================
-- 1. TIPOS E ENUMS
-- ==========================================
-- Define se é entrada ou saída de dinheiro
create type public.transaction_type as enum ('income', 'expense');

-- ==========================================
-- 2. TABELAS
-- ==========================================

-- Tabela: Contas (Carteira, Banco, etc.)
create table public.accounts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  name text not null,
  initial_balance numeric(12, 2) default 0.00, -- Suporta valores até 999 mil milhões
  is_default boolean default false
);

-- Tabela: Categorias
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  name text not null,
  icon text,
  type public.transaction_type not null default 'expense',
  is_editable boolean default true
);

-- Tabela: Transações (O coração do sistema)
create table public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  account_id bigint references public.accounts(id) on delete cascade not null,
  category_id bigint references public.categories(id) on delete set null, -- Se apagar a categoria, a transação fica "Sem categoria"
  amount numeric(12, 2) not null,
  date date not null default CURRENT_DATE,
  description text,
  type public.transaction_type not null
);

-- ==========================================
-- 3. SEGURANÇA (Row Level Security)
-- ==========================================

-- Ativar RLS em todas as tabelas
alter table public.accounts enable row level security;
alter table public.categories enable row level security;
alter table public.transactions enable row level security;

-- Política Genérica: O utilizador vê e edita APENAS o que é seu.
-- (Repetimos a lógica para manter o código limpo e seguro)

-- Accounts
create policy "Users manage their own accounts" on public.accounts for all
using ( auth.uid() = user_id ) with check ( auth.uid() = user_id );

-- Categories
create policy "Users manage their own categories" on public.categories for all
using ( auth.uid() = user_id ) with check ( auth.uid() = user_id );

-- Transactions
create policy "Users manage their own transactions" on public.transactions for all
using ( auth.uid() = user_id ) with check ( auth.uid() = user_id );

-- ==========================================
-- 4. PERFORMANCE (Índices)
-- ==========================================
-- Índices aceleram as queries quando tiveres milhares de transações
create index idx_transactions_user_date on public.transactions(user_id, date);
create index idx_transactions_account on public.transactions(account_id);
create index idx_categories_user on public.categories(user_id);

-- ==========================================
-- 5. AUTOMATIZAÇÃO E I18N (O Trigger)
-- ==========================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
declare
  user_lang text;
  -- Definição dos dados padrão (Categorias E Contas)
  default_data jsonb := '{
    "pt-BR": {
      "categories": [
        {"name": "Alimentação", "icon": "🍔", "type": "expense"},
        {"name": "Transporte", "icon": "🚌", "type": "expense"},
        {"name": "Moradia", "icon": "🏠", "type": "expense"},
        {"name": "Salário", "icon": "💰", "type": "income"}
      ],
      "accounts": [
        {"name": "Carteira (Dinheiro)", "is_default": true},
        {"name": "Conta Bancária", "is_default": false}
      ]
    },
    "en": {
      "categories": [
        {"name": "Food", "icon": "🍔", "type": "expense"},
        {"name": "Transport", "icon": "🚌", "type": "expense"},
        {"name": "Housing", "icon": "🏠", "type": "expense"},
        {"name": "Salary", "icon": "💰", "type": "income"}
      ],
      "accounts": [
        {"name": "Cash / Wallet", "is_default": true},
        {"name": "Bank Account", "is_default": false}
      ]
    }
  }';
  
  -- Variáveis auxiliares
  selected_data jsonb;
  item jsonb;
begin
  -- 1. Detetar língua
  user_lang := coalesce(new.raw_user_meta_data->>'language', 'en');
  
  -- 2. Selecionar dados (Fallback para EN se não encontrar)
  selected_data := default_data->user_lang;
  IF selected_data IS NULL THEN
    selected_data := default_data->'en';
  END IF;

  -- 3. Criar Contas Padrão
  for item in SELECT * FROM jsonb_array_elements(selected_data->'accounts')
  loop
    insert into public.accounts (user_id, name, is_default)
    values (new.id, item->>'name', (item->>'is_default')::boolean);
  end loop;

  -- 4. Criar Categorias Padrão
  for item in SELECT * FROM jsonb_array_elements(selected_data->'categories')
  loop
    insert into public.categories (user_id, name, icon, type)
    values (new.id, item->>'name', item->>'icon', (item->>'type')::public.transaction_type);
  end loop;

  return new;
end;
$$;

-- Ligar o gatilho
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();